version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python init_db.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db/resume_analyzer
    networks:
      - app-network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resume_analyzer
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run webview/streamlit_app.py
    volumes:
      - .:/app
    ports:
      - 8501:8501
    depends_on:
      - web
    environment:
      - API_URL=http://web:8000/api/v1
    networks:
      - app-network
  
  test:
    build:
      context: .
      target: test
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: