#docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://user:password@db/resume_analyzer
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resume_analyzer

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  streamlit:
    build: .
    command: streamlit run webview/streamlit_app.py
    volumes:
      - .:/app
    ports:
      - 8501:8501
    depends_on:
      - web

  worker:
    build: .
    command: python -m worker.worker  # Run as a module
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://user:password@db/resume_analyzer
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PYTHONPATH=/app  # Explicitly set PYTHONPATH
    restart: unless-stopped

volumes:
  postgres_data:
