#docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://user:password@db/resume_analyzer
      - RABBITMQ_HOST=rabbitmq

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=resume_analyzer

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  streamlit:
    build: .
    command: streamlit run webview/streamlit_app.py
    volumes:
      - .:/app
    ports:
      - 8501:8501
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  # RabbitMQ основной порт
      - 15672:15672  # RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  worker:
    build: .
    command: python worker/worker.py
    volumes:
      - .:/app
    depends_on:
      - web
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://user:password@db/resume_analyzer
      - RABBITMQ_HOST=rabbitmq

volumes:
  postgres_data: